gpu_ids: [0]

light_conf:
  N: 512
  L: 40
  B: 128
  H: 512
  P: 3
  X: 8
  R: 3
  norm: gLN
  num_spks: 2
  activate: relu
  causal: false
  # optimizer
  lr: !!float 1e-4
  # scheduler
  scheduler_mode: min
  scheduler_factor: 0.5
  patience: 2
  # DataLoader
  batch_size: 1
  num_workers: 4

train:
  epochs: 130
  early_stop: true
  patience: 5
  distributed_backend: ddp #dp, ddp, ddp_cpu, ddp2

resume:
  path: model/
  checkpoint: checkpoint