gpu_ids: [0,1]

light_conf:
  encoder_size: 21
  encoder_basis: 512
  out_channels: 128
  in_channels: 512
  num_blocks: 4
  upsampling_depth: 4
  num_sources: 2
  # optimizer
  lr: !!float 1e-4
  # scheduler
  scheduler_mode: min
  scheduler_factor: 0.5
  patience: 2
  # DataLoader
  batch_size: 4
  num_workers: 8

train:
  epochs: 2
  early_stop: true
  patience: 5
  distributed_backend: ddp #dp, ddp, ddp_cpu, ddp2

resume:
  path: model/
  checkpoint: checkpoint